version: "2"

services:
  web:
    build: ./
    restart: always
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html/
    environment:
      ENABLE_ENV_FILE: 1
      ENABLE_LOCALCONF: 1
      API_TOKEN: "<YOUR GITHUB API TOKEN>"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    links:
      - web
    volumes_from:
      - web